### ISSUE TITLE
Package run error

### ISSUE THREAD

**Issue by Jaky5155** [onSec-fr/Http-Asynchronous-Reverse-Shell#3]
Package run error
Prompt information：
“/Users/mac/Downloads/Http-Asynchronous-Reverse-Shell-master/HARS_Client/HARS/Main.cs(28,28): Error CS1061: 'object' does not contain a definition for 'AllowInsecureCertificate' and no accessible extension method 'AllowInsecureCertificate' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?) (CS1061) (HARS)”

**Comment by onSec-fr** [comment]
Hey @Jaky5155, i'll try to help !

Firstly, _AllowInsecureCertificate_ is a variable set in the _Config_ class and then used in the _Main.cs_ program.

1. Have you commented the line in Config ? If so, that's the problem. 
If you want to disable it, consider setting it to false : `public static bool AllowInsecureCertificate = false;`

2. How are you compiling the program? Via VS or cmd line? 
If so, please provide the command used. 

3. If you did it from VS, please provide your system infos. 

Ty.

**Comment by onSec-fr** [comment]
I will close the issue in 24h.
