### ISSUE TITLE
The process not hide in the task manager any more

### ISSUE THREAD

**Issue by xxnbyy** [onSec-fr/Http-Asynchronous-Reverse-Shell#5]
The process can been seen at the task manager now on this version
![图片](https://user-images.githubusercontent.com/20261647/81432080-da303080-9194-11ea-8cef-8ffde6dfd8f4.png)

![图片](https://user-images.githubusercontent.com/20261647/81432134-f59b3b80-9194-11ea-92d5-1893dc284aff.png)

**Comment by onSec-fr** [comment]
Hello,

Thanks for the info ! The task manager now shows the processes in the background. 
If you really want to "hide" the process, you have to be clever and disguise it or attach it to a legitimate process (but you risk triggering AVs)

Best Regards
